zuul:
  ignoredServices: "*"
  routes:
    api:
      path: /api/**


# Spring properties
spring:
  application:
     name: zuul

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

server:
  port: 8080
