server:
  port: 0

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  profiles:
    active: prod

  application:
       name: books

  datasource:
    url: jdbc:postgresql://localhost:5432/BookStoreBookService
    username: Dev
    password: dev

  jpa:
    hibernate:
      ddl-auto: validate
