# Spring properties
spring:
  application:
     name: reviews

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}


server:
  port: 0